version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    env_file:
      - ./.env.mysql.local

  fpm:
    image: renspoesse/uva-study-progress:latest
    depends_on:
      - db
    env_file:
      - ./.env
      - ./.env.local
      - ./.env.production
      - ./.env.production.local

  proxy:
    image: jwilder/nginx-proxy:alpine-0.7.0
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/ssl/certs:/etc/nginx/certs:ro

  web:
    image: renspoesse/uva-study-progress-web:latest
    depends_on:
      - fpm
    environment:
      VIRTUAL_HOST: studyprogress.uva.nl

volumes:
  data:
